# Generated by Django 3.0.8 on 2020-08-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomalydetection', '0002_auto_20200803_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
